# Generated by Django 5.2.4 on 2025-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('moderator', 'moderator'), ('regular', 'regular'), ('Subscriber', 'Subscriber')], default='regular', max_length=100),
        ),
    ]
