# Generated by Django 5.2.4 on 2025-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Subscriber', 'Subscriber'), ('moderator', 'moderator'), ('regular', 'regular')], default='regular', max_length=100),
        ),
    ]
