# Generated by Django 5.2.4 on 2025-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('regular', 'regular'), ('Subscriber', 'Subscriber'), ('moderator', 'moderator')], default='regular', max_length=100),
        ),
    ]
