# Generated by Django 5.2.4 on 2025-07-08 09:49

import SHINA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHINA', '0004_article_image_articleseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/no_image.png', max_length=255, upload_to=SHINA.models.Article.image_upload_to),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/no_image.png', max_length=255, upload_to=SHINA.models.ArticleSeries.image_upload_to),
        ),
    ]
